[package]
name = "oc-tool"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
oc-config = { path = "../oc-config" }
oc-global = { path = "../oc-global" }
oc-permission = { path = "../oc-permission" }
oc-session = { path = "../oc-session" }
serde_json = { workspace = true }
tracing = { workspace = true }
ureq = "2"
